### ISSUE TITLE
Unable to load asset: packages/progress_dialog/assets/double_ring_loading_io.gif

### ISSUE THREAD

**Issue by mokth** [CodingFries/progress_dialog#1]
under the progress_dialog_null_safe.dart

the origin  
Widget _progressWidget = Image.asset(
  'assets/double_ring_loading_io.gif',
  package: 'progress_dialog,           <-------------------    
);

should change to 
Widget _progressWidget = Image.asset(
  'assets/double_ring_loading_io.gif',
  package: 'progress_dialog_null_safe',   <-------------------    
);

if not will cause the error :
Unable to load asset: packages/progress_dialog/assets/double_ring_loading_io.gif

Thanks
TH Mok

**Comment by awais-amjed** [comment]
Fixed it.
Thanks for the issue : )
